---

- name: Create dictionary with installation variant for HANA Client 
  set_fact:
    client: "{{ item }}"
  loop: "{{ components }}"
  when: item.component == 'hana_client'

- name: Copy to Hana Client Installer
  win_copy: 
    src: "{{ hana_software_loc }}/{{ item.media_loc }}"
    dest: C:\Users\{{ ansible_user }}\install 
  loop: "{{ client.variants|flatten(levels=1) }}"
  when: item.os == 'WINDOWS'

- name: Install Hana Client
  win_shell: C:\Users\{{ ansible_user }}\install\{{ item.media_loc }}\{{ item.installer }} -a studio -b --path=C:\Users\{{ ansible_user }}\SAP_HANA_CLIENT
  args:
    creates: C:\Users\{{ ansible_user }}\SAP_HANA_CLIENT
  loop: "{{ client.variants|flatten(levels=1) }}"
  when: item.os == 'WINDOWS'
